### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Jun09yt** [JUANIMAN/PerfMTK#1]
Tried both v7 and v8 

Profile Buttons not working
Su -c permtk not working too

**Comment by JUANIMAN** [comment]
The app only works with the latest version of the module (v3.5), and this new version is not designed to be used from the terminal. If you want to use the terminal with version v3.5, here is the list of commands:

`su -c performance`
`su -c balanced`
`su -c powersave`
`su -c thermal_limit enable/disable`

However, these commands will not display any messages in the terminal. They will only apply the corresponding profile.
