### ISSUE TITLE
Boot loop on tab a7 lite T225, 3GB ram, CPU P22T 4x 2.30GHz and 4x1.8 GHZ (Stock Rom Android 14 1Ui Rooted Magisk)

### ISSUE THREAD

**Issue by Devahntei** [JUANIMAN/PerfMTK#3]
when installed to magisk and rebooted it will not move from "Tablet is starting" . then it would restart over and over again. will not load Safe mode aswell. Me Sad :(

**Comment by JUANIMAN** [comment]
Sorry for the inconvenience but the device you mention has a Helio P22T and its GPU is a PowerVR GE8320 and the module only supports Mali GPU.
