### ISSUE TITLE
Does it work on older Mediatek devices? 

### ISSUE THREAD

**Issue by IsHacker003** [JUANIMAN/PerfMTK#4]
I have a nokia 3 with MT6737 processor and Mali T720 MP1 GPU, running android 9. I installed this module and set it to "performance" profile, but it actually reduced my GPU frequency instead of increasing it (There is no way to view GPU frequency on Mediatek devices, but I know because of the choppy animations). Also it gives errors like "/system/devices/system/cpu/...: No such file or directory". I have the latest version (6.0)

**Comment by JUANIMAN** [comment]
Older chips do not have many of the kernel configurations that the module uses, it is recommended to use on devices with kernel version greater than 4.14.x. Sorry for the inconvenience
